In [19]:
import numpy as np
import imageio

face = imageio.imread('face.png')
zero = lambda t: t + 1
vfunc = np.vectorize(zero)
face2 = vfunc(face)

print(face2)
print(type(face))
print([face.shape, face.dtype])
print([face2.shape, face2.dtype])
imageio.imsave('face2.png', face2)

/tmp/ipykernel_3536/3103964564.py:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  face = imageio.imread('face.png')


[[[60.5 56.  65.5]
  [69.  64.5 74. ]
  [76.5 72.  82.5]
  ...
  [59.5 63.  37. ]
  [65.5 68.  41. ]
  [69.5 72.  45. ]]

 [[44.5 41.  50. ]
  [55.  51.5 60.5]
  [65.  61.  71.5]
  ...
  [59.  62.5 35.5]
  [67.  70.5 43.5]
  [73.  76.5 49.5]]

 [[36.5 33.  42. ]
  [47.  43.5 52.5]
  [57.5 54.  63. ]
  ...
  [58.5 63.  35.5]
  [66.5 71.  43.5]
  [72.  76.5 49. ]]

 ...

 [[43.5 53.  38. ]
  [47.  55.  40.5]
  [53.5 62.  46. ]
  ...
  [60.  79.  48.5]
  [59.5 78.5 48. ]
  [59.5 79.  47.5]]

 [[42.5 50.5 36. ]
  [47.5 55.5 41. ]
  [56.  63.5 48. ]
  ...
  [60.5 78.5 48. ]
  [60.  78.  47. ]
  [60.  78.  47. ]]

 [[42.5 50.5 37. ]
  [48.5 56.5 42. ]
  [55.5 63.  48.5]
  ...
  [60.  78.  47.5]
  [59.5 77.5 46.5]
  [59.  77.  46. ]]]
<class 'numpy.ndarray'>
[(768, 1024, 3), dtype('uint8')]
[(768, 1024, 3), dtype('float64')]


TypeError: Cannot handle this data type: (1, 1, 3), <f8